# Generated by Django 2.0.13 on 2019-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcart',
            options={'ordering': ['-created_at']},
        ),
    ]
