# Generated by Django 2.0.13 on 2019-05-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190531_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='content',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='creator',
        ),
        migrations.DeleteModel(
            name='AddCart',
        ),
    ]
